apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: LoadBalancer  # or NodePort for local
  selector:
    app: youtube-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
