apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-search
  template:
    metadata:
      labels:
        app: youtube-search
    spec:
      containers:
      - name: youtube-search-container
        image: sachinhatvalne01/youtube-search:latest
        ports:
        - containerPort: 80
